### ISSUE TITLE
Undefined array key "content_transition"

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/iivblock#1]
I'm experimenting with using this module in the Digital Agency / Zeever project, but I'm getting this warning. 

`Warning: Undefined array key "content_transition" in BlockIIV->getContent() (line 43 of /var/www/html/modules/iivblock/iivblock.block.inc).`

I've been hoping to debug this myself, but not sure if I'll have time soon. Any help would be appreciated.
https://github.com/backdrop-contrib/zeever/wiki

To test, simply spin up a Demo site on BackdropCMS.org and install the Digital Agency Recipe Package (and all dependencies).

**Comment by stpaultim** [comment]
@ininfoveritas

I asked ChatGPT for help and was provided this solution. 

This removes the warning from my site and the block still functions as I would expect. However, please review code carefully before merging.

https://github.com/backdrop-contrib/iivblock/pull/2

**Comment by stpaultim** [comment]
@hosef - Could you look at this PR for this issue and tell me if it makes sense. It's only two lines and should be pretty easy.

**Comment by ininfoveritas** [comment]
Hello Tim.
Thank your for this issue.
I'm so sorry because i have already done something for this lines but never push modifications... :-(
This will be corrected.

**Comment by stpaultim** [comment]
@ininfoveritas No problems. Thanks for sharing this module and supporting it.

**Comment by ininfoveritas** [comment]
@stpaultim Hello Tim, Does the new release work for you ?
Thank you again for your precious help by creating this issue.

**Comment by stpaultim** [comment]
Sorry for not replying sooner. Yes, your fix did address my problems. Thanks for your work on this module.

**Comment by ininfoveritas** [comment]
Perfect !
Thanks for your help and support.
